In [1]:
import numpy as np

a = np.arange(12).reshape(3,4)

In [2]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b = a.reshape(4 , -1)

In [4]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
c = b.reshape(-1, 4)

In [6]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
d = c.reshape(-1, 2, 3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
e = c.reshape(None, 4)

TypeError: 'NoneType' object cannot be interpreted as an integer